### ISSUE TITLE
Handler for ouxX format specifiers

### ISSUE THREAD

**Issue by msrspsr** [msrspsr/printf#12]
We need a handler for converting decimals to unsigned, octal, and hexadecimal in the main switch-case and supported functionality to work with their format specifiers. 

From `man 3 printf`:

> The  unsigned int argument is converted to unsigned octal (o), unsigned decimal (u), or unsigned hexadecimal (x and X) notation.  The  letters abcdef are used for x conversions; the letters ABCDEF are used for X conversions.  The precision, if any,  gives  the  minimum number  of  digits  that  must appear; if the converted value requires fewer digits, it is padded on the left with zeros.  The default precision is 1.  When 0 is printed with an explicit precision 0, the output is empty.

We're not tasked with handling field width, precision, length modifiers or flag characters yet. I think it may serve us to write things in a modular way that allows for plug-and-play.

<hr>

@Letsoken I can do unsigned decimal (`%u`) and hexadecimal (`%x` and `%X`) representations as you're doing `%d` and `%i`. If you want to do `%o` here, then we should be at parity.

Let me know if there's anything you need and how I can support.

**Comment by Letsoken** [comment]
Ok. I'll handle %o
